#!/usr/bin/env python3
"""Reject commit messages containing forbidden AI attribution patterns.

Usage (commit-msg hook): check_no_ai_attribution.py <commit-msg-file>
Usage (CI, batch check):  check_no_ai_attribution.py <file-with-all-messages>
"""

from __future__ import annotations

import re
import sys

FORBIDDEN: list[tuple[str, str]] = [
    (r"Generated by\s", "Generated by <outil>"),
    (r"Created by\s+(Cursor|Claude|Codex)", "Created by <outil>"),
    (r"Implemented by\s+(Cursor|Claude|Codex)", "Implemented by <outil>"),
    (r"(?i)^Co-authored-by:", "Co-authored-by:"),
    (r"AI-generated contribution", "AI-generated contribution"),
    (r"Assistant contribution", "Assistant contribution"),
]


def check_message(msg: str) -> bool:
    """Return True if the message is clean (no forbidden pattern)."""
    clean = True
    for pattern, label in FORBIDDEN:
        if re.search(pattern, msg, re.IGNORECASE | re.MULTILINE):
            print(
                f"ERREUR : attribution interdite détectée — « {label} »",
                file=sys.stderr,
            )
            clean = False
    if not clean:
        print(
            "Les messages de commit ne doivent pas mentionner un outil comme contributeur.",
            file=sys.stderr,
        )
    return clean


def main() -> int:
    """Entry point."""
    if len(sys.argv) < 2:
        print(
            "Usage: check_no_ai_attribution.py <commit-msg-file>",
            file=sys.stderr,
        )
        return 1

    with open(sys.argv[1]) as fh:
        msg = fh.read()

    return 0 if check_message(msg) else 1


if __name__ == "__main__":
    sys.exit(main())
